[build]
base = "apps/frontend"
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/api/*"
to = "https://kalender-hijriyah-api.vercel.app/:splat"
status = 200
force = true